# Generated by Django 4.2.4 on 2023-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
