# Generated by Django 4.2.4 on 2023-08-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_emp_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_register',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
