# Generated by Django 4.2.4 on 2023-08-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_emp_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='fileimage',
            field=models.FileField(default=1, upload_to='djangoapp/static'),
            preserve_default=False,
        ),
    ]
