# Generated by Django 4.2.4 on 2023-08-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_fileupload_fileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioname', models.CharField(max_length=20)),
                ('audio', models.FileField(upload_to='djangoapp/static')),
                ('videoname', models.CharField(max_length=20)),
                ('video', models.FileField(upload_to='djangoapp/static')),
                ('pdfname', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
    ]
